{
  parserClass="com.intellij.lang.cloudslang.CloudSlangParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="CloudSlang"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.lang.cloudslang.plugin.psi"
  psiImplPackage="com.intellij.lang.cloudslang.plugin.psi"

  elementTypeHolderClass="com.intellij.lang.cloudslang.plugin.psi.CloudSlangTypes"
  elementTypeClass="com.intellij.lang.cloudslang.parsing.CloudSlangElementType"
  tokenTypeClass="com.intellij.lang.cloudslang.parsing.CloudSlangTokenType"
}

simpleFile ::= item_*


private item_ ::= (body_|COMMENT|CRLF)

private body_ ::= namespace_ operation_

private namespace_ ::= NAMESPACE_KEYWORD NAMESPACE_SEPARATOR SPACE NAMESPACE_VALUE

private operation_ ::= OPERATION_KEYWORD NAMESPACE_SEPARATOR operation_name_ operation_inputs_ operation_action_

private operation_name_ ::=  OPERATION_NAME_KEYWORD NAMESPACE_SEPARATOR SPACE NAMESPACE_VALUE

private operation_inputs_ ::=  operation_inputs_header_ operation_input_list_
private operation_inputs_header_ ::=  OPERATION_INPUTS_KEYWORD NAMESPACE_SEPARATOR
private operation_input_list_ ::= operation_input_el_*
private operation_input_el_ ::=  MINUS SPACE NAMESPACE_VALUE

private operation_action_ ::=  operation_action_header_ java_action_header_ java_action_class_name_ java_action_method_name_
private operation_action_header_ ::=  OPERATION_ACTION_KEYWORD NAMESPACE_SEPARATOR
private java_action_header_ ::=  OPERATION_JAVA_ACTION_KEYWORD NAMESPACE_SEPARATOR
private java_action_class_name_ ::=  OPERATION_JAVA_ACTION_CLASS_NAME_KEYWORD NAMESPACE_SEPARATOR SPACE NAMESPACE_VALUE
private java_action_method_name_ ::=  OPERATION_JAVA_ACTION_METHOD_NAME_KEYWORD NAMESPACE_SEPARATOR SPACE NAMESPACE_VALUE



